spring:
  data.mongodb.uri: ${MONGODB_URI}

telegram-api:
  token: ${TELEGRAM_API_TOKEN}
  set-webhook-url: https://api.telegram.org/bot${telegram-api.token}/setWebhook

techtwits:
  bot:
    base-url: ${BOT_BASE_URL}
    webhook-callback-url: ${techtwits.bot.base-url}/webhook/${telegram-api.token}
  data:
    import: false
    resourceFilePath: ${RESOURCE_FILE_PATH}
